[package]
name = "TTO_DragOnline"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enigo = "0.0.14"
inputbot = "0.5.0"
winit = "0.25.0"
winapi = "0.3.9"
user32-sys = "0.2.0"